### ISSUE TITLE
Colour differentiation issue on Navbar

### ISSUE THREAD

**Issue by Arya-A-Nair** [EshanTrivedi21/MyPortfolio#1]
while hovering on any of the 5 buttons on the navbar, the colour of the button changes to a darker shade but so does the navbar. This might reduce the visual appeal of the webpage.

**Comment by EshanTrivedi21** [comment]
change kiya hai bro thoda try checking out again

Eshan Kalp Trivedi

Research & Development

Team KJSCE Robocon

***@***.***

Phone: 9920742199

<https://wa.me/9920742199>[image:
https://www.linkedin.com/in/vishrut-deshmukh-42b1ba226/]
<http://www.linkedin.com/in/eshan-trivedi21h-42b1ba226/>[image:
https://www.instagram.com/its.beetroot/]
<https://www.instagram.com/eshan.trivedii/>
